apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-dashboard
subjects:
  - kind: ServiceAccount
    name: k8s-dashboard
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-dashboard
  apiGroup: rbac.authorization.k8s.io
