apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-dashboard
rules:
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pods', 'nodes']
    verbs: ['get', 'watch', 'list']
