apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-dashboard-backend-node-configmap
data:
  PORT: '4000'
  CLUSTER_DEPLOYMENT: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-backend-node-depl
  labels:
    app: k8s-dashboard-backend-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-dashboard-backend-node
  template:
    metadata:
      labels:
        app: k8s-dashboard-backend-node
    spec:
      containers:
        - name: k8s-dashboard-backend-node
          image: ghcr.io/lolei/k8s-dashboard-backend-node:1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: k8s-dashboard-backend-node-configmap
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 4000
              path: /api/health
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 4000
              path: /api/health
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-backend-node-svc
  labels:
    run: k8s-dashboard-backend-node
spec:
  selector:
    app: k8s-dashboard-backend-node
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
