# Courtesy of https://gitlab.com/cocainefarm/gnulag/catinator/-/blob/master/Containerfile

# ------------------------------------------------------------------------------
# Cargo Build Stage
# ------------------------------------------------------------------------------

FROM rust:1.53-alpine as cargo-build

RUN rustup default nightly && rustup update

WORKDIR /work

COPY . .

RUN apk add --no-cache musl-dev
RUN cargo build --release

# ------------------------------------------------------------------------------
# Final Stage
# ------------------------------------------------------------------------------

FROM alpine:3.13

COPY --from=cargo-build /work/target/release/k8s-dashboard-backend /usr/local/bin

CMD ["/usr/local/bin/k8s-dashboard-backend"]
