# Inspiration courtesy of:
# * https://gitlab.com/cocainefarm/gnulag/catinator/-/blob/master/Containerfile
# * https://gitlab.com/cocainefarm/pastor/-/blob/master/Containerfile

# ------------------------------------------------------------------------------
# Cargo Build Stage
# ------------------------------------------------------------------------------

FROM rust:1.53-alpine as cargo-build

RUN rustup default nightly && rustup update

WORKDIR /work

COPY . .

RUN apk add --no-cache musl-dev
RUN cargo build --release

# ------------------------------------------------------------------------------
# Final Stage
# ------------------------------------------------------------------------------

FROM alpine:3.13

WORKDIR /app

COPY --from=cargo-build /work/target/release/k8s-dashboard-backend .

EXPOSE 4000

CMD ["./k8s-dashboard-backend"]
